### ISSUE TITLE
В случае если переменные среды изменены в одном playbook, а перезагрузка происходит в другом, то узлы не перезагружаются

### ISSUE THREAD

**Issue by Kasen** [picodata/ansible-cartridge#4]
Пример:
```yaml
- name: Configure instance parameters
  hosts: all
  roles:
    - tarantool.cartridge
  become: true
  become_user: root
  gather_facts: false
  vars:
    cartridge_scenario:
      - configure_instance

- name: Restart replicas
  hosts: replicas
  serial: 4
  roles:
    - tarantool.cartridge
  become: true
  become_user: root
  gather_facts: false
  vars:
    cartridge_scenario:
      - restart_instance
      - wait_instance_started
      - wait_members_alive
      - wait_cluster_has_no_issues
```
